// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1, arg2) {
  return window['go']['wails']['App']['Emit'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['wails']['App']['Greet'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['wails']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['App']['Startup'](arg1);
}
