// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function CommitChanges(arg1:string,arg2:string,arg3:string,arg4:string):Promise<git.CommitInfo>;

export function InspectRepository(arg1:string):Promise<git.RepoDetails>;
