// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitChanges(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['GitHandler']['CommitChanges'](arg1, arg2, arg3, arg4);
}

export function InspectRepository(arg1) {
  return window['go']['wails']['GitHandler']['InspectRepository'](arg1);
}
