// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2) {
  return window['go']['wails']['HubHandler']['CreateProject'](arg1, arg2);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['wails']['HubHandler']['CreateSession'](arg1, arg2, arg3);
}

export function GetMetrics(arg1) {
  return window['go']['wails']['HubHandler']['GetMetrics'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['wails']['HubHandler']['GetSessionMessages'](arg1);
}

export function ListAgents() {
  return window['go']['wails']['HubHandler']['ListAgents']();
}

export function ListConnectors() {
  return window['go']['wails']['HubHandler']['ListConnectors']();
}

export function ListProjects() {
  return window['go']['wails']['HubHandler']['ListProjects']();
}

export function ListSessions(arg1) {
  return window['go']['wails']['HubHandler']['ListSessions'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['HubHandler']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function ToggleConnector(arg1) {
  return window['go']['wails']['HubHandler']['ToggleConnector'](arg1);
}
