// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateProject(arg1:string,arg2:string):Promise<domain.Project>;

export function CreateSession(arg1:string,arg2:string,arg3:Array<string>):Promise<domain.Session>;

export function GetMetrics(arg1:number):Promise<Array<domain.Metric>>;

export function GetSessionMessages(arg1:string):Promise<Array<domain.Message>>;

export function ListAgents():Promise<Array<domain.Agent>>;

export function ListConnectors():Promise<Array<domain.Connector>>;

export function ListProjects():Promise<Array<domain.Project>>;

export function ListSessions(arg1:string):Promise<Array<domain.Session>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Message>;

export function ToggleConnector(arg1:string):Promise<domain.Connector>;
