// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateCompletion(arg1) {
  return window['go']['wails']['LLMHandler']['GenerateCompletion'](arg1);
}

export function StreamPrompt(arg1, arg2) {
  return window['go']['wails']['LLMHandler']['StreamPrompt'](arg1, arg2);
}
