// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';

export function GenerateCompletion(arg1:llm.CompletionRequest):Promise<llm.CompletionResponse>;

export function StreamPrompt(arg1:string,arg2:llm.CompletionRequest):Promise<void>;
