// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {telemetry} from '../models';

export function GetMetricsSnapshot():Promise<telemetry.MetricsSnapshot>;
