// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnqueueLLMTask(arg1, arg2) {
  return window['go']['wails']['TaskHandler']['EnqueueLLMTask'](arg1, arg2);
}

export function GetRecentTasks(arg1) {
  return window['go']['wails']['TaskHandler']['GetRecentTasks'](arg1);
}

export function GetTaskByID(arg1) {
  return window['go']['wails']['TaskHandler']['GetTaskByID'](arg1);
}
