// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';

export function EnqueueLLMTask(arg1:string,arg2:Record<string, any>):Promise<task.Job>;

export function GetRecentTasks(arg1:number):Promise<Array<task.Job>>;

export function GetTaskByID(arg1:string):Promise<task.Job>;
